/**
 * Seed data generated from the laws JSON (marijuana, guns, gambling,
 * death_penalty, minimum_wage) for all 50 US states.
 *
 * Run via your seeder or import directly:
 *   import { LawMasterSeed, StateLawSeed } from "./stateLawsFromJson";
 */

// State name → code map derived from states.js seed
const STATE_CODE_MAP = {
  Alabama: "AL", Alaska: "AK", Arizona: "AZ", Arkansas: "AR",
  California: "CA", Colorado: "CO", Connecticut: "CT", Delaware: "DE",
  Florida: "FL", Georgia: "GA", Hawaii: "HI", Idaho: "ID",
  Illinois: "IL", Indiana: "IN", Iowa: "IA", Kansas: "KS",
  Kentucky: "KY", Louisiana: "LA", Maine: "ME", Maryland: "MD",
  Massachusetts: "MA", Michigan: "MI", Minnesota: "MN", Mississippi: "MS",
  Missouri: "MO", Montana: "MT", Nebraska: "NE", Nevada: "NV",
  "New Hampshire": "NH", "New Jersey": "NJ", "New Mexico": "NM",
  "New York": "NY", "North Carolina": "NC", "North Dakota": "ND",
  Ohio: "OH", Oklahoma: "OK", Oregon: "OR", Pennsylvania: "PA",
  "Rhode Island": "RI", "South Carolina": "SC", "South Dakota": "SD",
  Tennessee: "TN", Texas: "TX", Utah: "UT", Vermont: "VT",
  Virginia: "VA", Washington: "WA", "West Virginia": "WV",
  Wisconsin: "WI", Wyoming: "WY",
};

// ─── LawMaster entries (one per category) ────────────────────────────────────

export const LawMasterSeed = [
  {
    law_key: "marijuana",
    title: "Marijuana Laws",
    short_title: "Marijuana",
    description_global:
      "State-level marijuana legality covering recreational use, medical programs, and decriminalization status.",
    domain: "Criminal",
    sub_domain: "Controlled Substances",
    tags: ["marijuana", "cannabis", "drugs", "recreational", "medical"],
    severity: "high",
    risk_score: 75,
    source_type: "migration",
    is_active: true,
    is_deleted: false,
  },
  {
    law_key: "guns",
    title: "Gun & Firearm Laws",
    short_title: "Guns",
    description_global:
      "State-level firearm regulations including carry permits, concealed carry, and constitutional carry status.",
    domain: "Criminal",
    sub_domain: "Firearms",
    tags: ["guns", "firearms", "carry", "second-amendment", "concealed"],
    severity: "high",
    risk_score: 70,
    source_type: "migration",
    is_active: true,
    is_deleted: false,
  },
  {
    law_key: "gambling",
    title: "Gambling Laws",
    short_title: "Gambling",
    description_global:
      "State-level gambling regulations covering casinos, sports betting, lotteries, and online gambling.",
    domain: "Civil",
    sub_domain: "Gaming & Wagering",
    tags: ["gambling", "casino", "sports-betting", "lottery", "online-gambling"],
    severity: "medium",
    risk_score: 40,
    source_type: "migration",
    is_active: true,
    is_deleted: false,
  },
  {
    law_key: "death_penalty",
    title: "Death Penalty",
    short_title: "Death Penalty",
    description_global:
      "Whether a state has an active death penalty, a moratorium, or has abolished capital punishment entirely.",
    domain: "Criminal",
    sub_domain: "Capital Punishment",
    tags: ["death-penalty", "capital-punishment", "execution", "moratorium"],
    severity: "critical",
    risk_score: 95,
    source_type: "migration",
    is_active: true,
    is_deleted: false,
  },
  {
    law_key: "minimum_wage",
    title: "Minimum Wage",
    short_title: "Min. Wage",
    description_global:
      "State minimum wage rates and whether the state uses the federal rate of $7.25/hr or has its own higher rate.",
    domain: "Labor",
    sub_domain: "Wage & Hour",
    tags: ["minimum-wage", "labor", "employment", "wages"],
    severity: "low",
    risk_score: 20,
    source_type: "migration",
    is_active: true,
    is_deleted: false,
  },
];

// ─── Raw JSON data (inlined so no runtime file read is needed) ────────────────

const RAW = {
  marijuana: {
    Alabama: { status: "Illegal", notes: "No medical or recreational program" },
    Alaska: { status: "Legal (Recreational + Medical)", notes: "Legal for adults 21+ since 2015" },
    Arizona: { status: "Legal (Recreational + Medical)", notes: "Prop 207 passed 2020, adults 21+" },
    Arkansas: { status: "Legal (Medical Only)", notes: "Medical program since 2016" },
    California: { status: "Legal (Recreational + Medical)", notes: "Fully legal since 2016, Prop 64" },
    Colorado: { status: "Legal (Recreational + Medical)", notes: "First state to legalize, 2012" },
    Connecticut: { status: "Legal (Recreational + Medical)", notes: "Legal since 2021 for adults 21+" },
    Delaware: { status: "Legal (Recreational + Medical)", notes: "Legalized 2023, adults 21+" },
    Florida: { status: "Legal (Medical Only)", notes: "Medical only; recreational on 2024 ballot" },
    Georgia: { status: "Legal (Medical Only)", notes: "Limited medical CBD oil only" },
    Hawaii: { status: "Legal (Medical Only)", notes: "Medical since 2000; recreational pending" },
    Idaho: { status: "Illegal", notes: "One of strictest states, no exceptions" },
    Illinois: { status: "Legal (Recreational + Medical)", notes: "Legal since Jan 2020, adults 21+" },
    Indiana: { status: "Illegal", notes: "No medical program, CBD oil limited" },
    Iowa: { status: "Legal (Medical Only)", notes: "Medical CBD program only" },
    Kansas: { status: "Illegal", notes: "No medical or recreational program" },
    Kentucky: { status: "Legal (Medical Only)", notes: "Medical program signed into law 2023" },
    Louisiana: { status: "Legal (Medical Only)", notes: "Medical program active since 2016" },
    Maine: { status: "Legal (Recreational + Medical)", notes: "Legal since 2016, adults 21+" },
    Maryland: { status: "Legal (Recreational + Medical)", notes: "Recreational legal since July 2023" },
    Massachusetts: { status: "Legal (Recreational + Medical)", notes: "Legal since 2016 via ballot" },
    Michigan: { status: "Legal (Recreational + Medical)", notes: "Legal since 2018, adults 21+" },
    Minnesota: { status: "Legal (Recreational + Medical)", notes: "Legalized 2023, adults 21+" },
    Mississippi: { status: "Legal (Medical Only)", notes: "Medical program since 2022" },
    Missouri: { status: "Legal (Recreational + Medical)", notes: "Recreational legal since Dec 2022" },
    Montana: { status: "Legal (Recreational + Medical)", notes: "Legal since 2021, adults 21+" },
    Nebraska: { status: "Illegal", notes: "Decrim effort failed; no program" },
    Nevada: { status: "Legal (Recreational + Medical)", notes: "Legal since 2017, adults 21+" },
    "New Hampshire": { status: "Decriminalized", notes: "Small amounts decrim; medical program" },
    "New Jersey": { status: "Legal (Recreational + Medical)", notes: "Legal since 2021, adults 21+" },
    "New Mexico": { status: "Legal (Recreational + Medical)", notes: "Legal since June 2021" },
    "New York": { status: "Legal (Recreational + Medical)", notes: "Legal since 2021, adults 21+" },
    "North Carolina": { status: "Decriminalized", notes: "Small amounts decrim; no medical" },
    "North Dakota": { status: "Legal (Medical Only)", notes: "Medical since 2016; recreational failed" },
    Ohio: { status: "Legal (Recreational + Medical)", notes: "Recreational legalized Nov 2023" },
    Oklahoma: { status: "Legal (Medical Only)", notes: "One of most accessible medical programs" },
    Oregon: { status: "Legal (Recreational + Medical)", notes: "Legal since 2015; psilocybin also legal" },
    Pennsylvania: { status: "Legal (Medical Only)", notes: "Medical since 2016; active discussions" },
    "Rhode Island": { status: "Legal (Recreational + Medical)", notes: "Legal since May 2022" },
    "South Carolina": { status: "Illegal", notes: "No program; limited CBD bill" },
    "South Dakota": { status: "Legal (Medical Only)", notes: "Medical only; recreational repealed" },
    Tennessee: { status: "Illegal", notes: "No medical or recreational program" },
    Texas: { status: "Legal (Medical Only)", notes: "Compassionate use program very limited" },
    Utah: { status: "Legal (Medical Only)", notes: "Medical only, no home cultivation" },
    Vermont: { status: "Legal (Recreational + Medical)", notes: "Legal since 2018; retail sales 2022" },
    Virginia: { status: "Legal (Recreational + Medical)", notes: "Legal since 2021, adults 21+" },
    Washington: { status: "Legal (Recreational + Medical)", notes: "Legal since 2012, adults 21+" },
    "West Virginia": { status: "Legal (Medical Only)", notes: "Medical program since 2017" },
    Wisconsin: { status: "Illegal", notes: "CBD oil limited; no medical program" },
    Wyoming: { status: "Illegal", notes: "No medical or recreational program" },
  },
  guns: {
    Alabama: { status: "Permitless Carry", notes: "Open & concealed carry, no permit required" },
    Alaska: { status: "Permitless Carry", notes: "No permit needed for any carry" },
    Arizona: { status: "Permitless Carry", notes: "Constitutional carry since 2010" },
    Arkansas: { status: "Permitless Carry", notes: "Permitless carry enacted 2013" },
    California: { status: "Heavily Restricted", notes: "May-issue; strict assault weapon ban" },
    Colorado: { status: "Shall-Issue", notes: "Shall-issue; red flag law in effect" },
    Connecticut: { status: "Restricted", notes: "May-issue; strict background checks" },
    Delaware: { status: "Shall-Issue", notes: "Shall-issue concealed carry permits" },
    Florida: { status: "Permitless Carry", notes: "Permitless carry enacted 2023" },
    Georgia: { status: "Permitless Carry", notes: "Constitutional carry since 2022" },
    Hawaii: { status: "Heavily Restricted", notes: "Very restrictive; few permits issued" },
    Idaho: { status: "Permitless Carry", notes: "No permit needed; very permissive" },
    Illinois: { status: "Restricted", notes: "FOID card required; Chicago strict" },
    Indiana: { status: "Permitless Carry", notes: "Constitutional carry since 2022" },
    Iowa: { status: "Permitless Carry", notes: "Permitless carry signed 2021" },
    Kansas: { status: "Permitless Carry", notes: "Constitutional carry since 2015" },
    Kentucky: { status: "Permitless Carry", notes: "No permit needed since 2019" },
    Louisiana: { status: "Permitless Carry", notes: "Constitutional carry since 2024" },
    Maine: { status: "Permitless Carry", notes: "Permitless carry since 2015" },
    Maryland: { status: "Restricted", notes: "May-issue; handgun permit required" },
    Massachusetts: { status: "Heavily Restricted", notes: "May-issue; assault weapon ban; strict" },
    Michigan: { status: "Shall-Issue", notes: "Shall-issue; universal background checks" },
    Minnesota: { status: "Shall-Issue", notes: "Shall-issue; red flag law 2023" },
    Mississippi: { status: "Permitless Carry", notes: "Constitutional carry since 2016" },
    Missouri: { status: "Permitless Carry", notes: "No permit needed since 2017" },
    Montana: { status: "Permitless Carry", notes: "Permitless carry statewide since 2021" },
    Nebraska: { status: "Permitless Carry", notes: "Constitutional carry signed 2023" },
    Nevada: { status: "Shall-Issue", notes: "Shall-issue; background checks required" },
    "New Hampshire": { status: "Permitless Carry", notes: "Constitutional carry since 2017" },
    "New Jersey": { status: "Heavily Restricted", notes: "May-issue; assault weapon ban; strict" },
    "New Mexico": { status: "Shall-Issue", notes: "Shall-issue concealed carry" },
    "New York": { status: "Heavily Restricted", notes: "May-issue; among strictest in US" },
    "North Carolina": { status: "Shall-Issue", notes: "Shall-issue; pistol purchase permit" },
    "North Dakota": { status: "Permitless Carry", notes: "Constitutional carry since 2017" },
    Ohio: { status: "Permitless Carry", notes: "Permitless carry since 2022" },
    Oklahoma: { status: "Permitless Carry", notes: "Constitutional carry since 2019" },
    Oregon: { status: "Restricted", notes: "Measure 114: permit-to-purchase 2022" },
    Pennsylvania: { status: "Shall-Issue", notes: "Shall-issue; preemption law" },
    "Rhode Island": { status: "May-Issue", notes: "May-issue; discretionary permits" },
    "South Carolina": { status: "Permitless Carry", notes: "Constitutional carry enacted 2023" },
    "South Dakota": { status: "Permitless Carry", notes: "No permit needed since 2019" },
    Tennessee: { status: "Permitless Carry", notes: "Permitless carry since 2021" },
    Texas: { status: "Permitless Carry", notes: "Constitutional carry since 2021" },
    Utah: { status: "Permitless Carry", notes: "Permitless carry since 2021" },
    Vermont: { status: "Permitless Carry", notes: "Never required permits; oldest policy" },
    Virginia: { status: "Shall-Issue", notes: "Shall-issue; universal background checks" },
    Washington: { status: "Restricted", notes: "Universal background checks; assault ban" },
    "West Virginia": { status: "Permitless Carry", notes: "Constitutional carry since 2016" },
    Wisconsin: { status: "Shall-Issue", notes: "Shall-issue; open carry legal" },
    Wyoming: { status: "Permitless Carry", notes: "Constitutional carry since 2011" },
  },
  gambling: {
    Alabama: { status: "Illegal", notes: "No casinos; charity bingo only" },
    Alaska: { status: "Legal (Lottery Only)", notes: "Charitable gaming only; no casinos" },
    Arizona: { status: "Fully Legal", notes: "Tribal casinos + sports betting legal" },
    Arkansas: { status: "Fully Legal", notes: "Casinos legal; sports betting 2022" },
    California: { status: "Legal (Casinos Only)", notes: "Tribal casinos; sports betting pending" },
    Colorado: { status: "Fully Legal", notes: "Casinos + sports betting legal 2019" },
    Connecticut: { status: "Fully Legal", notes: "Tribal casinos + sports betting 2021" },
    Delaware: { status: "Fully Legal", notes: "First state with sports betting 2018" },
    Florida: { status: "Legal (Casinos Only)", notes: "Tribal casinos; sports betting disputed" },
    Georgia: { status: "Legal (Lottery Only)", notes: "Lottery only; no casinos or sports" },
    Hawaii: { status: "Illegal", notes: "Most restrictive; gambling fully banned" },
    Idaho: { status: "Legal (Lottery Only)", notes: "Lottery only; tribal gaming limited" },
    Illinois: { status: "Fully Legal", notes: "Casinos + sports betting legal 2019" },
    Indiana: { status: "Fully Legal", notes: "Casinos + sports betting legal 2019" },
    Iowa: { status: "Fully Legal", notes: "Casinos + sports betting legal 2019" },
    Kansas: { status: "Fully Legal", notes: "State casinos + sports betting 2022" },
    Kentucky: { status: "Fully Legal", notes: "Horse racing historic; sports bet 2023" },
    Louisiana: { status: "Fully Legal", notes: "Casinos + sports betting legal 2021" },
    Maine: { status: "Fully Legal", notes: "Tribal casinos + sports betting 2022" },
    Maryland: { status: "Fully Legal", notes: "Casinos + sports betting legal 2021" },
    Massachusetts: { status: "Fully Legal", notes: "Casinos + sports betting legal 2023" },
    Michigan: { status: "Fully Legal", notes: "Casinos + online gambling + sports" },
    Minnesota: { status: "Legal (Casinos Only)", notes: "Tribal casinos; sports betting pending" },
    Mississippi: { status: "Legal (Casinos Only)", notes: "Casinos legal; sports betting limited" },
    Missouri: { status: "Legal (Lottery Only)", notes: "Lottery + horse racing; sports pending" },
    Montana: { status: "Sports Betting Legal", notes: "Sports betting via lottery kiosks 2019" },
    Nebraska: { status: "Legal (Casinos Only)", notes: "Casinos approved 2020; sports pending" },
    Nevada: { status: "Fully Legal", notes: "Original gambling capital of the US" },
    "New Hampshire": { status: "Sports Betting Legal", notes: "Sports betting 2019; no casinos" },
    "New Jersey": { status: "Fully Legal", notes: "Atlantic City casinos + online gambling" },
    "New Mexico": { status: "Legal (Casinos Only)", notes: "Tribal casinos; no sports betting" },
    "New York": { status: "Fully Legal", notes: "Casinos + sports betting legal 2021" },
    "North Carolina": { status: "Sports Betting Legal", notes: "Sports betting 2023; no commercial casinos" },
    "North Dakota": { status: "Legal (Casinos Only)", notes: "Tribal casinos + charitable gaming" },
    Ohio: { status: "Fully Legal", notes: "Casinos + sports betting legal 2023" },
    Oklahoma: { status: "Legal (Casinos Only)", notes: "Large tribal casino industry; no sports" },
    Oregon: { status: "Sports Betting Legal", notes: "Sports betting via lottery; tribal casinos" },
    Pennsylvania: { status: "Fully Legal", notes: "Casinos + sports betting + online gambling" },
    "Rhode Island": { status: "Fully Legal", notes: "Two casinos + sports betting legal" },
    "South Carolina": { status: "Illegal", notes: "Only lottery; gambling largely banned" },
    "South Dakota": { status: "Fully Legal", notes: "Deadwood casinos + sports betting 2021" },
    Tennessee: { status: "Sports Betting Legal", notes: "Online sports betting only; no casinos" },
    Texas: { status: "Legal (Lottery Only)", notes: "Lottery + horse racing; casinos banned" },
    Utah: { status: "Illegal", notes: "Total gambling ban including lottery" },
    Vermont: { status: "Sports Betting Legal", notes: "Sports betting launched 2024" },
    Virginia: { status: "Fully Legal", notes: "Casinos + sports betting legal 2020" },
    Washington: { status: "Legal (Casinos Only)", notes: "Tribal casinos; sports betting 2021" },
    "West Virginia": { status: "Fully Legal", notes: "Casinos + online gambling + sports" },
    Wisconsin: { status: "Legal (Casinos Only)", notes: "Tribal casinos only; no sports betting" },
    Wyoming: { status: "Sports Betting Legal", notes: "Sports betting legal 2021; no casinos" },
  },
  death_penalty: {
    Alabama: { status: "Active", notes: "Active; uses nitrogen gas since 2024" },
    Alaska: { status: "Abolished", notes: "Abolished 1957; no executions since" },
    Arizona: { status: "Active", notes: "Active; resumed executions 2022" },
    Arkansas: { status: "Active", notes: "Active; mass executions 2017" },
    California: { status: "Moratorium", notes: "Gov. Newsom moratorium since 2019" },
    Colorado: { status: "Abolished", notes: "Abolished March 2020" },
    Connecticut: { status: "Abolished", notes: "Abolished 2012" },
    Delaware: { status: "Abolished", notes: "Supreme Court struck down 2016" },
    Florida: { status: "Active", notes: "Active; recently expanded scope" },
    Georgia: { status: "Active", notes: "Active executions" },
    Hawaii: { status: "Abolished", notes: "Abolished 1957; never had execution" },
    Idaho: { status: "Active", notes: "Active; few executions in modern era" },
    Illinois: { status: "Abolished", notes: "Abolished 2011" },
    Indiana: { status: "Active", notes: "Active; no recent executions" },
    Iowa: { status: "Abolished", notes: "Abolished 1965" },
    Kansas: { status: "Active", notes: "Active law but no executions since 1965" },
    Kentucky: { status: "Active", notes: "Active; no recent executions" },
    Louisiana: { status: "Active", notes: "Active; resumed debate 2024" },
    Maine: { status: "Abolished", notes: "Abolished 1887; longest ban in US" },
    Maryland: { status: "Abolished", notes: "Abolished 2013" },
    Massachusetts: { status: "Abolished", notes: "Abolished 1984" },
    Michigan: { status: "Abolished", notes: "Abolished 1846; first US state to do so" },
    Minnesota: { status: "Abolished", notes: "Abolished 1911" },
    Mississippi: { status: "Active", notes: "Active executions" },
    Missouri: { status: "Active", notes: "Active; frequent executions" },
    Montana: { status: "Active", notes: "Active; few recent executions" },
    Nebraska: { status: "Active", notes: "Voters reinstated 2016; no executions" },
    Nevada: { status: "Active", notes: "Active; no recent executions" },
    "New Hampshire": { status: "Abolished", notes: "Abolished 2019" },
    "New Jersey": { status: "Abolished", notes: "Abolished 2007" },
    "New Mexico": { status: "Abolished", notes: "Abolished 2009" },
    "New York": { status: "Abolished", notes: "Court struck down 2004; legislature 2008" },
    "North Carolina": { status: "Moratorium", notes: "De facto moratorium; legal challenges" },
    "North Dakota": { status: "Abolished", notes: "Abolished 1973" },
    Ohio: { status: "Moratorium", notes: "Gov. moratorium since 2019" },
    Oklahoma: { status: "Active", notes: "Active; high execution rate" },
    Oregon: { status: "Moratorium", notes: "Gov. moratorium since 2011" },
    Pennsylvania: { status: "Moratorium", notes: "Gov. moratorium since 2015" },
    "Rhode Island": { status: "Abolished", notes: "Abolished 1984" },
    "South Carolina": { status: "Active", notes: "Resumed executions 2022" },
    "South Dakota": { status: "Active", notes: "Active; resumed 2012" },
    Tennessee: { status: "Active", notes: "Active; moratorium on nitrogen gas" },
    Texas: { status: "Active", notes: "Highest execution rate in the US" },
    Utah: { status: "Active", notes: "Active; allows firing squad" },
    Vermont: { status: "Abolished", notes: "Abolished 1964" },
    Virginia: { status: "Abolished", notes: "Abolished March 2021" },
    Washington: { status: "Abolished", notes: "Supreme Court abolished 2018" },
    "West Virginia": { status: "Abolished", notes: "Abolished 1965" },
    Wisconsin: { status: "Abolished", notes: "Abolished 1853" },
    Wyoming: { status: "Active", notes: "Active law; rare executions" },
  },
  minimum_wage: {
    Alabama: { status: "Uses Federal Rate", notes: "$7.25/hr — no state minimum wage law" },
    Alaska: { status: "Above Federal", notes: "$11.73/hr (2024)" },
    Arizona: { status: "Above Federal", notes: "$14.35/hr (2024)" },
    Arkansas: { status: "Above Federal", notes: "$11.00/hr (2024)" },
    California: { status: "Above Federal", notes: "$16.00/hr; fast food workers $20/hr" },
    Colorado: { status: "Above Federal", notes: "$14.42/hr (2024)" },
    Connecticut: { status: "Above Federal", notes: "$15.69/hr (2024)" },
    Delaware: { status: "Above Federal", notes: "$13.25/hr (2024)" },
    Florida: { status: "Above Federal", notes: "$13.00/hr; rising to $15 by 2026" },
    Georgia: { status: "Uses Federal Rate", notes: "$5.15 state law but federal $7.25 applies" },
    Hawaii: { status: "Above Federal", notes: "$14.00/hr (2024)" },
    Idaho: { status: "Uses Federal Rate", notes: "$7.25/hr — uses federal minimum" },
    Illinois: { status: "Above Federal", notes: "$14.00/hr; rising to $15 by 2025" },
    Indiana: { status: "Uses Federal Rate", notes: "$7.25/hr — uses federal minimum" },
    Iowa: { status: "Uses Federal Rate", notes: "$7.25/hr — uses federal minimum" },
    Kansas: { status: "Uses Federal Rate", notes: "$7.25/hr — uses federal minimum" },
    Kentucky: { status: "Uses Federal Rate", notes: "$7.25/hr — uses federal minimum" },
    Louisiana: { status: "Uses Federal Rate", notes: "$7.25/hr — no state minimum wage law" },
    Maine: { status: "Above Federal", notes: "$14.15/hr (2024)" },
    Maryland: { status: "Above Federal", notes: "$15.00/hr (2024)" },
    Massachusetts: { status: "Above Federal", notes: "$15.00/hr (2024)" },
    Michigan: { status: "Above Federal", notes: "$10.33/hr; increasing gradually" },
    Minnesota: { status: "Above Federal", notes: "$10.85/hr large employers (2024)" },
    Mississippi: { status: "Uses Federal Rate", notes: "$7.25/hr — no state minimum wage law" },
    Missouri: { status: "Above Federal", notes: "$12.30/hr (2024)" },
    Montana: { status: "Above Federal", notes: "$10.30/hr (2024)" },
    Nebraska: { status: "Above Federal", notes: "$12.00/hr (2024)" },
    Nevada: { status: "Above Federal", notes: "$12.00/hr (2024)" },
    "New Hampshire": { status: "Uses Federal Rate", notes: "$7.25/hr — uses federal minimum" },
    "New Jersey": { status: "Above Federal", notes: "$15.49/hr (2024)" },
    "New Mexico": { status: "Above Federal", notes: "$12.00/hr (2024)" },
    "New York": { status: "Above Federal", notes: "$16.00/hr NYC; $15.00 upstate (2024)" },
    "North Carolina": { status: "Uses Federal Rate", notes: "$7.25/hr — uses federal minimum" },
    "North Dakota": { status: "Uses Federal Rate", notes: "$7.25/hr — uses federal minimum" },
    Ohio: { status: "Above Federal", notes: "$10.45/hr (2024)" },
    Oklahoma: { status: "Uses Federal Rate", notes: "$7.25/hr — uses federal minimum" },
    Oregon: { status: "Above Federal", notes: "$14.70/hr standard; $15.45 Portland metro" },
    Pennsylvania: { status: "Uses Federal Rate", notes: "$7.25/hr — uses federal minimum" },
    "Rhode Island": { status: "Above Federal", notes: "$14.00/hr (2024)" },
    "South Carolina": { status: "Uses Federal Rate", notes: "$7.25/hr — no state minimum wage law" },
    "South Dakota": { status: "Above Federal", notes: "$11.20/hr (2024)" },
    Tennessee: { status: "Uses Federal Rate", notes: "$7.25/hr — no state minimum wage law" },
    Texas: { status: "Uses Federal Rate", notes: "$7.25/hr — uses federal minimum" },
    Utah: { status: "Uses Federal Rate", notes: "$7.25/hr — uses federal minimum" },
    Vermont: { status: "Above Federal", notes: "$13.67/hr (2024)" },
    Virginia: { status: "Above Federal", notes: "$12.00/hr (2024)" },
    Washington: { status: "Above Federal", notes: "$16.28/hr — highest in US (2024)" },
    "West Virginia": { status: "Above Federal", notes: "$8.75/hr" },
    Wisconsin: { status: "Uses Federal Rate", notes: "$7.25/hr — uses federal minimum" },
    Wyoming: { status: "Uses Federal Rate", notes: "$5.15 state but federal $7.25 applies" },
  },
};

// Human-readable titles per law key
const LAW_TITLES = {
  marijuana: "Marijuana Law",
  guns: "Gun & Firearm Law",
  gambling: "Gambling Law",
  death_penalty: "Death Penalty",
  minimum_wage: "Minimum Wage",
};

// ─── Build StateLaw seed (250 records) ───────────────────────────────────────

export const StateLawSeed = Object.entries(RAW).flatMap(([lawKey, stateMap]) =>
  Object.entries(stateMap).map(([stateName, { status, notes }]) => ({
    state_code: STATE_CODE_MAP[stateName],
    country_code: "US",
    law_key: lawKey,
    jurisdiction_type: "state",
    title: `${LAW_TITLES[lawKey]}: ${status}`,
    summary: status,
    details: notes,
    status: "active",
    version: 1,
    change_source: "migration",
    is_active: true,
    is_deleted: false,
  }))
);
