/**
 * Automated law-ingestion pipeline.
 *
 *   Phase A — Wikipedia: re-scrape the mapped "by state" categories, hash each
 *             row, and only normalize+draft rows whose source CHANGED (cheap).
 *   Phase B — Research: for categories with no scrapeable table, have Claude
 *             generate per-state drafts ONCE (gated by generator_version).
 *
 * Every output is a status:"draft" StateLaw → flows through admin review.
 * A LawIngestionJob row records each run (surfaces in the admin dashboard).
 *
 * baseline mode: record current Wikipedia hashes WITHOUT drafting or calling
 * Claude — run once so the first real run doesn't flood the queue with drafts
 * for laws you already have. Skips Phase B.
 *
 * NOTE: babel config does not support `??` — use `||`.
 */

import fs from "fs";
import path from "path";
import crypto from "crypto";
import { spawn } from "child_process";
import StateLaw from "../../../database/models/StateLaw";
import LawSourceState from "../../../database/models/LawSourceState";
import LawIngestionJob from "../../../database/models/LawIngestionJob";
import { classifyLegality, penaltySeverity } from "../../helpers/lawClassifier";
import { STATE_NAME_BY_CODE } from "../../helpers/usStates";
import { normalizeRow, generateRow, ingestModel } from "./claude";

const ROOT = path.resolve(__dirname, "..", "..", "..");
const SCRAPER = "scraped/script/scrape-laws-per-state.mjs";
const WIKI_DIR = path.join(ROOT, "scraped", "laws-per-state");

// Scraped slug → app law_key.
const CATEGORY_TO_LAWKEY = {
  cannabis: "marijuana",
  capital_punishment: "death_penalty",
  death_penalty: "death_penalty",
  minimum_wage: "minimum_wage",
  age_of_consent: "age_of_consent",
  abortion: "abortion",
  gambling: "gambling",
  gun: "guns",
  guns: "guns",
};

// Phase B — categories with no clean by-state table, generated by Claude.
// Configurable via LAW_INGEST_RESEARCH="fireworks,window_tint" (comma list).
// Bump RESEARCH_VERSION to force regeneration of all research laws.
const RESEARCH_VERSION = "v1";
const TOPIC_LABELS = {
  fireworks: "Consumer fireworks",
  window_tint: "Car window tint",
  radar_detector: "Radar detector use",
  knife: "Knife carry",
  helmet: "Motorcycle helmet requirement",
};
const RESEARCH_CATEGORIES = (process.env.LAW_INGEST_RESEARCH ||
  "fireworks,window_tint,radar_detector")
  .split(",")
  .map((s) => s.trim().toLowerCase())
  .filter(Boolean)
  .map((law_key) => ({ law_key, topic: TOPIC_LABELS[law_key] || humanize(law_key) }));

function humanize(key) {
  return key.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}
function sha256(v) {
  return crypto.createHash("sha256").update(typeof v === "string" ? v : JSON.stringify(v)).digest("hex");
}

function execNode(relPath, args = []) {
  return new Promise((resolve, reject) => {
    const child = spawn("node", [relPath, ...args], { cwd: ROOT, stdio: "inherit" });
    child.on("error", reject);
    child.on("exit", (code) => (code === 0 ? resolve() : reject(new Error(`${relPath} exited ${code}`))));
  });
}

async function upsertLedger(state_code, law_key, source, hash, genVer, extra = {}) {
  await LawSourceState.updateOne(
    { state_code, law_key, source },
    { $set: { content_hash: hash, generator_version: genVer, last_seen_at: new Date(), ...extra } },
    { upsert: true }
  );
}

async function createDraft(state_code, law_key, stateName, rec, fallbackUrl) {
  const latest = await StateLaw.findOne({ state_code, law_key }).sort({ version: -1 }).select("version").lean();
  const keyPoints = Array.isArray(rec.key_points) ? rec.key_points : [];
  const summary = rec.summary || "See details.";
  const details = [keyPoints.join("\n"), rec.penalty_text].filter(Boolean).join("\n").trim() || summary;
  const sourceUrl = rec.source_url || fallbackUrl || "";
  await StateLaw.create({
    state_code,
    law_key,
    title: `${stateName} — ${humanize(law_key)}`,
    summary,
    details,
    key_points: keyPoints,
    traveler_note: rec.traveler_note || "",
    legality: rec.legality || classifyLegality(law_key, summary),
    legality_label: rec.legality_label || "",
    penalty_text: rec.penalty_text || "",
    penalty_severity: rec.penalty_severity || penaltySeverity(rec.penalty_text || ""),
    statute_reference: rec.statute_reference || "",
    official_url: sourceUrl,
    sources: sourceUrl ? [{ label: "Source", url: sourceUrl }] : [],
    status: "draft",
    version: latest ? latest.version + 1 : 1,
    change_source: "api",
    verified: false,
  });
}

export async function runLawIngestion(opts = {}) {
  const baseline = !!opts.baseline;
  const job = await LawIngestionJob.create({
    job_id: `ingest-${Date.now()}`,
    file_name: `auto-ingestion-${new Date().toISOString().slice(0, 10)}${baseline ? "-baseline" : ""}`,
    upload_source: "system",
    template_version: "v1",
    status: "processing",
  });

  const counts = { total: 0, success: 0, skipped: 0, error: 0 };
  const tag = `[lawIngestion]${baseline ? " (baseline)" : ""}`;
  console.log(`${tag} start — model ${ingestModel()}`);

  try {
    // ── Phase A: Wikipedia ────────────────────────────────────────────────────
    console.log(`${tag} scraping Wikipedia categories…`);
    await execNode(SCRAPER, ["--all"]);

    const files = fs.existsSync(WIKI_DIR) ? fs.readdirSync(WIKI_DIR).filter((f) => f.endsWith(".json")) : [];
    for (const f of files) {
      const raw = JSON.parse(fs.readFileSync(path.join(WIKI_DIR, f), "utf8"));
      const slug = (raw.category || f.replace(/\.json$/, "")).toLowerCase();
      const law_key = (CATEGORY_TO_LAWKEY[slug] || slug).toLowerCase();
      for (const row of raw.rows || []) {
        const code = String(row.state_code || "").trim().toUpperCase();
        if (!code) continue;
        counts.total++;
        const hash = sha256(row.columns || {});
        const existing = await LawSourceState.findOne({ state_code: code, law_key, source: "wikipedia" });
        if (existing && existing.content_hash === hash) {
          counts.skipped++;
          await upsertLedger(code, law_key, "wikipedia", hash, "", { last_status: "skipped" });
          continue;
        }
        if (baseline) {
          counts.skipped++;
          await upsertLedger(code, law_key, "wikipedia", hash, "", { last_status: "baseline" });
          continue;
        }
        try {
          const rec = await normalizeRow({ topic: humanize(law_key), state: row.state, columns: row.columns });
          await createDraft(code, law_key, row.state, rec, raw.source_url);
          await upsertLedger(code, law_key, "wikipedia", hash, "", { last_status: "drafted", last_drafted_at: new Date() });
          counts.success++;
        } catch (e) {
          counts.error++;
          await upsertLedger(code, law_key, "wikipedia", hash, "", { last_status: "error", last_error: e.message });
          console.error(`${tag} ${code}/${law_key}: ${e.message}`);
        }
      }
    }

    // ── Phase B: Claude research (additive, generated once) ────────────────────
    if (!baseline && RESEARCH_CATEGORIES.length) {
      console.log(`${tag} researching ${RESEARCH_CATEGORIES.length} no-table categories…`);
      for (const { law_key, topic } of RESEARCH_CATEGORIES) {
        for (const [code, stateName] of Object.entries(STATE_NAME_BY_CODE)) {
          const existing = await LawSourceState.findOne({ state_code: code, law_key, source: "claude-research" });
          if (existing && existing.generator_version === RESEARCH_VERSION) {
            counts.skipped++;
            continue;
          }
          counts.total++;
          try {
            const rec = await generateRow({ topic, state: stateName });
            await createDraft(code, law_key, stateName, rec, rec.source_url);
            await upsertLedger(code, law_key, "claude-research", sha256(rec), RESEARCH_VERSION, {
              last_status: "drafted",
              last_drafted_at: new Date(),
            });
            counts.success++;
          } catch (e) {
            counts.error++;
            await upsertLedger(code, law_key, "claude-research", "", RESEARCH_VERSION, {
              last_status: "error",
              last_error: e.message,
            });
            console.error(`${tag} ${code}/${law_key} (research): ${e.message}`);
          }
        }
      }
    }

    const status = counts.error > 0 ? (counts.success > 0 ? "partial" : "failed") : "completed";
    await LawIngestionJob.updateOne(
      { _id: job._id },
      { total_rows: counts.total, success_rows: counts.success, error_rows: counts.error, skipped_rows: counts.skipped, status }
    );
    console.log(`${tag} done — drafted ${counts.success}, skipped ${counts.skipped}, errors ${counts.error} (status ${status})`);
    return { job_id: job.job_id, status, baseline, ...counts };
  } catch (e) {
    await LawIngestionJob.updateOne({ _id: job._id }, { status: "failed", ...counts });
    console.error(`${tag} FAILED: ${e.message}`);
    throw e;
  }
}
